<?php 
    require 'header.php';
?>

<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia aut similique, tempora voluptatem dolor modi delectus, Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cupiditate quibusdam ipsam aut ducimus magnam numquam saepe nihil possimus temporibus hic tempore totam odit at error est, placeat voluptatem? Delectus, nihil. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa repellat qui totam nisi! Libero sapiente illo dolor necessitatibus tempora magni ratione saepe, inventore quod blanditiis cum atque a beatae tenetur! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa molestias, quam impedit, alias voluptates exercitationem, laboriosam voluptas magnam porro eius vitae vero? Tempore error reprehenderit quas provident porro, neque fuga! Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, adipisci. Provident tenetur, nisi recusandae perferendis sint repellat ea vero laudantium accusamus, culpa consequuntur dicta sequi possimus reiciendis fugiat optio rerum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates ipsum reprehenderit expedita veniam magni qui, molestiae optio praesentium repellat ad dolore delectus explicabo, doloribus aperiam dolor obcaecati. Nobis, cupiditate quae? deserunt nesciunt ea maiores doloribus reiciendis architecto nemo, vel illo eum itaque officia porro. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Provident atque nemo eligendi omnis explicabo eaque blanditiis voluptatem consectetur culpa? Alias libero maiores magni sit eos mollitia nisi maxime, doloremque explicabo. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae, ducimus ratione ullam perspiciatis dolorum ea soluta alias quam libero, voluptas accusantium exercitationem accusamus id. Sequi corporis quis officia repellat exercitationem! Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, magnam. Tenetur voluptatibus repellendus eum minima distinctio atque, ea odit dolor commodi doloribus reiciendis illo iure laborum fuga sint temporibus suscipit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore eveniet sequi qui eius. Optio nobis tenetur, quasi quam totam impedit blanditiis cumque similique itaque consequatur sequi reprehenderit ipsa incidunt odit. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam veritatis voluptates accusamus ut magnam iure ipsa explicabo officia vitae id libero incidunt ad sequi reprehenderit, corporis adipisci eveniet ullam quis! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vel vero, dignissimos id, eos deleniti facere tempore ratione nulla laborum dolorem minima dolor ut iure quidem veritatis praesentium cupiditate obcaecati blanditiis? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas reiciendis ex, quisquam molestias iusto quibusdam minus, sint alias, voluptatibus laborum laudantium. Eveniet numquam nihil iste sit quasi odit, natus ex.</p>

<?php 
    require 'footer.php';
?>
